name: ajcf-server

on:
  pull_request:
    paths:
      - "ajcf-server/**/*.ts"
  push:
    branches:
      - master

jobs:
  build:
    name: Build ajcf-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node & yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   with:
      #     path: ajcf-server/node_modules
      #     key: ajcf-server-${{ hashFiles('ajcf-server/yarn.lock') }}

  test:
    name: Test ajcf-server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Instal packages
        run: cd ajcf-server && yarn install
      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   with:
      #     path: ajcf-server/node_modules
      #     key: ajcf-server-${{ hashFiles('ajcf-server/yarn.lock') }}
      - name: Test
        run: cd ajcf-server && yarn tsc -b && yarn test

  deploy:
    name: Deploy ajcf-server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Instal packages
        run: cd ajcf-server && yarn install
      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   with:
      #     path: ajcf-server/node_modules
      #     key: ajcf-server-${{ hashFiles('ajcf-server/yarn.lock') }}
      - name: Deploy
        env:
          ENV: prod
          STAGE: prod
          DB_USERNAME: admin
          DB_PORT: 35896
          DB_NAME: ajcf-server-prod
          HELLOASSO_USERNAME: ajcf
          SEND_IN_BLUE_TEMPLATE_WELCOME_ID: 4
          SEND_IN_BLUE_TEMPLATE_SUBSCRIPTION_REMINDER_ID: 5
          SEND_IN_BLUE_EVENTS_LISTS_FOLDER_ID: 12
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
          HELLOASSO_PASSWORD: ${{ secrets.HELLOASSO_PASSWORD }}
          HELLOASSO_V5_CLIENT_ID: ${{ secrets.HELLOASSO_V5_CLIENT_ID }}
          HELLOASSO_V5_CLIENT_SECRET: ${{ secrets.HELLOASSO_V5_CLIENT_SECRET }}
        run: cd ajcf-server && yarn sls deploy

